name: Deploy

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust (rustup)
      run: rustup update stable --no-self-update && rustup default stable
    - name: Install mdBook
      run: cargo install mdbook --locked
    - name: Build book
      run: mdbook build mdbook
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: mdbook/book
        
    # - name: Deploy to GitHub
    #   env:
    #     GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
    #   run: |
    #     touch mdbook/book/.nojekyll
    #     curl -LsSf https://raw.githubusercontent.com/rust-lang/simpleinfra/master/setup-deploy-keys/src/deploy.rs | rustc - -o /tmp/deploy
    #     cd mdbook/book
    #     /tmp/deploy
